### PR TITLE
add royalroad adapter

### PR DESCRIPTION
**Pull request by wassname**
- tested on 8 stories https://royalroadl.com/fiction/3689, 3984,7301, 5369, 1587, 3056, 1992, 4676
- tested in calibre on 3978

Reminder to self: If this is accepted we should remove royalroadl from unsupported sites on the wiki [here](https://github.com/JimmXinu/FanFicFare/wiki/SupportedSites)

### CODE REVIEW

**Comment by JimmXinu** [comment]
Accepted.  Thanks!

FYI, I changed 'rating' to 'stars' and added the sections to the INI files.  You'll need to add stars to title page in personal.ini to see them.  'rating' has a different meaning in the standard metadata.

I've posted a plugin test version in [the usual place](http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025).

**Comment by wassname** [comment]
Oh good point, thanks for looking it over.

**Comment by JimmXinu** [comment]
There's a [problem report](http://www.mobileread.com/forums/showthread.php?p=3417038#post3417038) over on the plugin forum.  Would you mind taking a look at it?

FYI, I usually wait and edit the SupportSites list after the new site is in an official release.  No big deal, but it's a bit more accurate that way.

**Comment by wassname** [comment]
No problems I'll fix it shortly

**Comment by wassname** [comment]
Fixes are in #146

**Comment by cryzed** [comment]
Really nice work, thank you for contributing.

**Comment by wassname** [comment]
Thanks :)

**Comment by cryzed** [comment]
Heh :^).

**Pull request merged**
