### PR TITLE
Python2/3 Dual Code

### PR DESCRIPTION
**Pull request by JimmXinu**
Borrowing from @mcepl's PR #321, I've made my own py2/py3 dual version.

I'm making this PR so @mcepl (and other users) can comment on it, if they like.  No disrespect intended to @mcepl, but I wanted to be sure I understood all the changes.

I've tested this branch on windows 10 with all sites (except the dozen or so where the site is broken) and all output formats, in English and 'wide byte' (I used Japanese).  I've done cursory testing with using it in Calibre Plugin and Web Service.

Outstanding issues:
- Need to test CLI on linux (&MacOS?)
- Problems with `--save-cache` feature?
- Test outputs on additional readers
- Re-examine Nook cover issue kludge
- Review remaining `encode()`/`decode()` calls for possible replacement with `ensure_text()` or `ensure_binary()`
- `pip` packaging changes

I did consider rebasing my ugly commit history to cover it up, but better to leave it here.  I do plan a squash merge when it goes into master.

### CODE REVIEW

**Comment by cryzed** [comment]
I think this is a really good effort and I'm glad you decided to do it. I know that it's probably grueling and boring work -- I definitely appreciate it.

**Comment by mcepl** [comment]
Well, for start: could you rebase on the top of the current master, please?

**Comment by JimmXinu** [comment]
As requested by @mcepl, I've rebased and fixed the version conflict that was the only difference.

I didn't know that would also apparently discard the previously posted comments...

**Comment by mcepl** [comment]
```
matej@mitmanek: ~$ fanficfare https://www.fanfiction.net/s/9261035/1/Operation-Wandless
Traceback (most recent call last):
  File "/home/matej/repos/FanFicFare/fanficfare/cli.py", line 57, in <module>
    from calibre_plugins.fanficfare_plugin.fanficfare import adapters, writers, exceptions
ImportError: No module named 'calibre_plugins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matej/.local/bin/fanficfare", line 9, in <module>
    load_entry_point('FanFicFare', 'console_scripts', 'fanficfare')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2719, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2379, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2385, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/matej/repos/FanFicFare/fanficfare/cli.py", line 66, in <module>
    from fanficfare import adapters, writers, exceptions
  File "/home/matej/repos/FanFicFare/fanficfare/adapters/__init__.py", line 30, in <module>
    from .. import configurable as configurable
  File "/home/matej/repos/FanFicFare/fanficfare/configurable.py", line 20, in <module>
    import exceptions
ImportError: No module named 'exceptions'
matej@mitmanek: ~$ 
```

**Comment by JimmXinu** [comment]
That one was a pretty easy fix.  I'm kind of surprised it I didn't find other, similar problems.

In related news, first test on linux--mine, at least)--successful. :-)

**Comment by hawkrives** [comment]
I can try it on macOS this afternoon (US/Central) with a few sites I frequent?

**Comment by JimmXinu** [comment]
@hawkrives - Sure, that would be great.  

However, remember this is an early test version--do backups first.

**Comment by hawkrives** [comment]
Yeah, I'll be copying my stories into a new folder, if I don't just run this in a VM for complete isolation :-)

**Comment by mcepl** [comment]
@hawkrives Don't worry, it doesn't ramble all over your hard-drive, but the current folder could be in jeopardy.

@JimmXinu with the last commits (on dde61749), it seems like I have it working with Python 3.6.5 on RHEL-7. Tested with fanfiction.net, www.siye.co.uk, and archiveofourown.org. Thank you!

**Comment by JimmXinu** [comment]
@hawkrives, thanks for helping!

### `utf8` issues

> ```
> fanficfare --debug 'http://hpfanficarchive.com/stories/viewstory.php?sid=689'
> ```
> 
> Every chapter said:
> 
> ```
> FFF: DEBUG: 2018-08-04 09:40:38,743: configurable.py(992): code failed:utf8
> FFF: DEBUG: 2018-08-04 09:40:38,744: configurable.py(993): 'utf-8' codec can't decode byte 0x92 in position 21148: invalid start byte
> ```

Do you have a `website_encodings` setting under `[www.hpfanficarchive.com]` or `[overrides]` that specifies `utf8` first?  Or don't have `default.ini` in the normal place?  Because the default for that site is `website_encodings:Windows-1252,utf8`.  I only see that warning if I put `utf8` first.

> `http://www.fictionalley.org/authors/drt/JOTP.html`
> `http://www.mediaminer.org/fanfic/view_st.php/21744`

Same thing again with both of these.  I only see that warning if I explicitly change the order of the encodings to put `utf8` first.

I wonder if it might be that MacOS doesn't like `Windows-1252`, but if that were in the list first, it should have reported it failing before trying `utf8`.

---

### Update image issues

> And finally, I decided that I should try the `--update-epub` flag… 
> 
> ```
> fanficfare --debug http://royalroadl.com/fiction/8894 --update-epub
> ```
> 
> I'm going to try to attach the source epub I updated – [Everybody Loves Large Chests-rylrdl_8894.epub.zip](https://github.com/JimmXinu/FanFicFare/files/2259567/Everybody.Loves.Large.Chests-rylrdl_8894.epub.zip).

Thanks for including the source epub.  Because I think that's what's wrong here.  _All_ of the image tags in it are only showing ``.  Update needs `` tags to have both `src` and `longdesc` attributes in the saved epub to work correctly.

I'm not sure how you ended up with an epub without those attributes, actually.  FFF should _always_ save them, even if you change the `keep_html_attrs` settings.  I can't get FFF to output an epub without them...

Have you done any post-processing on that epub?

**Comment by hawkrives** [comment]
@JimmXinu Thanks for digging in to it!

I installed this branch in a virtualenv, so I would assume that fff will use the `fanficfare/defaults.ini` file in this repository? Regardless, if you're not seeing it, it's probably something specific to my system. I can try to dig into it more later on.

Regarding the `` tags in the epub… I don't _think_ I've done any post-processing on it, but I may have? It would have been downloaded with FanFicFare, most likely through Calibre, if that affects anything.

**Comment by JimmXinu** [comment]
Actually, after I move both my `defaults.ini` and `personal.ini` aside so they can't be found, I think I see both of the problems you do--the encoding issue and the `` tag issue.

I'll take look at how virtualenv differs from normal WRT `defaults.ini` placement.

**Comment by JimmXinu** [comment]
I've setup a VM running a MacOS image, installed `pip`, `virtualenv`, `virtualenvwrapper`, created a virtenv, and installed FFF in it.  And it can find `defaults.ini` just fine.

So I think that @hawkrives's missing `defaults.ini` is specific to their setup--or at least, their type of setup, which appears different `/Users/rives/.local/share/virtualenvs/FanFicFare-JEMXcSRO/lib/python3.7/site-packages/FanFicFare-2.37.0-py3.7.egg/fanficfare/` vs my `/Users/retief/virtualenvs/fff/lib/python2.7/site-packages/fanficfare/`

@hawkrives, what is your testing setup?

**Comment by JimmXinu** [comment]
- I've added changes to fix the `` tag with no attributes issue plus some other stuff.

I've left the warning output from `epubutils.py` when it finds ``s without attrs because this isn't the only way that could happen.  Plus, they're just warnings, not stopping errors.

- I'd still like to try and figure out why @hawkrives didn't have `defaults.ini` loaded.  I do not intend to pull the encoding list for each site back into code.

**Comment by hawkrives** [comment]
@JimmXinu It looks like your virtualenv was using Python 2? I was definitely testing with Python 3.

So, if I use Python's venv module to create the virtualenv, I don't have any issues – I guess it loads `defaults.ini` just fine. Or, at least, I don't get unicode errors.

```bash
$ python3 -m venv ./venv
$ source ./venv/bin/activate
$ python3 setup.py install
$ which fanficfare
/Users/rives/Projects/FanFicFare/venv/bin/fanficfare
$ fanficfare --debug 'http://hpfanficarchive.com/stories/viewstory.php?sid=689'
FFF: DEBUG: 2018-08-05 21:00:28,796: cli.py(87): Python Version:3.7.0 (default, Jun 29 2018, 20:14:27)
[Clang 9.0.0 (clang-900.0.39.2)]
FFF: DEBUG: 2018-08-05 21:00:28,847: adapter_hpfanficarchivecom.py(79): URL: https://hpfanficarchive.com/stories/viewstory.php?sid=689
FFF: DEBUG: 2018-08-05 21:00:28,847: configurable.py(1083): #####################################
pagecache(GET) MISS: https://hpfanficarchive.com/stories/viewstory.php?sid=689
FFF: INFO: 2018-08-05 21:00:30,810: base_writer.py(183): Save directly to file: Harry Potter & the Curse's Cure-hpffa_689.epub
```

If, however, I use [pipenv](https://docs.pipenv.org/) to create it, fanficfare doesn't seem to be able to find the `defaults.ini` – or, at least, I _get_ unicode errors.

```bash
$ pipenv shell --three
$ python3 setup.py install
$ which fanficfare
/Users/rives/.local/share/virtualenvs/FanFicFare-JEMXcSRO/bin/fanficfare
$ fanficfare --debug 'http://hpfanficarchive.com/stories/viewstory.php?sid=689'
FFF: DEBUG: 2018-08-05 20:59:25,256: cli.py(87): Python Version:3.7.0 (default, Jun 29 2018, 20:14:27)
[Clang 9.0.0 (clang-900.0.39.2)]
FFF: DEBUG: 2018-08-05 20:59:25,276: adapter_hpfanficarchivecom.py(79): URL: https://hpfanficarchive.com/stories/viewstory.php?sid=689
FFF: DEBUG: 2018-08-05 20:59:25,277: configurable.py(1083): #####################################
pagecache(GET) MISS: https://hpfanficarchive.com/stories/viewstory.php?sid=689
FFF: DEBUG: 2018-08-05 20:59:28,892: configurable.py(992): code failed:utf8
FFF: DEBUG: 2018-08-05 20:59:28,892: configurable.py(993): 'utf-8' codec can't decode byte 0x92 in position 21148: invalid start byte
FFF: INFO: 2018-08-05 20:59:29,255: base_writer.py(183): Save directly to file: Harry Potter & the Curse's Cure-hpffa_689.epub
```

Since it seems to be an issue with my tooling, and not with the Python 3 version, I think think it's intriguing, but not really a problem (how many people are going to install FanFicFare inside a Pipenv venv?)

**Comment by hawkrives** [comment]
using 870fce58c4e6adc11603e6ec4cf4fcf078745fed

with `python3 -m venv ./venv`:

```
fanficfare --debug 'http://hpfanficarchive.com/stories/viewstory.php?sid=689'
FFF: DEBUG: 2018-08-05 21:33:28,852: cli.py(87): Python Version:3.7.0 (default, Jun 29 2018, 20:14:27)
[Clang 9.0.0 (clang-900.0.39.2)]
FFF: DEBUG: 2018-08-05 21:33:28,860: cli.py(535): confs list:['/Users/rives/Projects/FanFicFare/venv/lib/python3.7/site-packages/FanFicFare-2.37.0-py3.7.egg/fanficfare/defaults.ini', '/Users/rives/.fanficdownloader/defaults.ini', '/Users/rives/.fanficfare/defaults.ini', 'defaults.ini', '/Users/rives/.fanficdownloader/personal.ini', '/Users/rives/.fanficfare/personal.ini', 'personal.ini']
FFF: DEBUG: 2018-08-05 21:33:28,888: cli.py(536): read confs:['/Users/rives/Projects/FanFicFare/venv/lib/python3.7/site-packages/FanFicFare-2.37.0-py3.7.egg/fanficfare/defaults.ini', '/Users/rives/.fanficfare/personal.ini']
FFF: DEBUG: 2018-08-05 21:33:28,901: adapter_hpfanficarchivecom.py(79): URL: https://hpfanficarchive.com/stories/viewstory.php?sid=689
FFF: DEBUG: 2018-08-05 21:33:28,902: configurable.py(1083): #####################################
pagecache(GET) MISS: https://hpfanficarchive.com/stories/viewstory.php?sid=689
FFF: INFO: 2018-08-05 21:33:30,652: base_writer.py(183): Save directly to file: Harry Potter & the Curse's Cure-hpffa_689.epub
```

with `pipenv shell --three`:

```
fanficfare --debug 'http://hpfanficarchive.com/stories/viewstory.php?sid=689'
FFF: DEBUG: 2018-08-05 21:34:04,124: cli.py(87): Python Version:3.7.0 (default, Jun 29 2018, 20:14:27)
[Clang 9.0.0 (clang-900.0.39.2)]
FFF: DEBUG: 2018-08-05 21:34:04,132: cli.py(535): confs list:['/Users/rives/.local/share/virtualenvs/FanFicFare-JEMXcSRO/lib/python3.7/site-packages/FanFicFare-2.37.0-py3.7.egg/fanficfare/defaults.ini', '/Users/rives/.fanficdownloader/defaults.ini', '/Users/rives/.fanficfare/defaults.ini', 'defaults.ini', '/Users/rives/.fanficdownloader/personal.ini', '/Users/rives/.fanficfare/personal.ini', 'personal.ini']
FFF: DEBUG: 2018-08-05 21:34:04,133: cli.py(536): read confs:['/Users/rives/.fanficfare/personal.ini']
FFF: DEBUG: 2018-08-05 21:34:04,144: adapter_hpfanficarchivecom.py(79): URL: https://hpfanficarchive.com/stories/viewstory.php?sid=689
FFF: DEBUG: 2018-08-05 21:34:04,145: configurable.py(1083): #####################################
pagecache(GET) MISS: https://hpfanficarchive.com/stories/viewstory.php?sid=689
FFF: DEBUG: 2018-08-05 21:34:08,397: configurable.py(992): code failed:utf8
FFF: DEBUG: 2018-08-05 21:34:08,398: configurable.py(993): 'utf-8' codec can't decode byte 0x92 in position 21148: invalid start byte
FFF: INFO: 2018-08-05 21:34:08,743: base_writer.py(183): Save directly to file: Harry Potter & the Curse's Cure-hpffa_689.epub
```

So, it sure seems like the pipenv version doesn't have `defaults.ini` in its egg.

Do you have any easy way to look into an `.egg`? I've attached it, if that's of any use. [venv-FanFicFare-2.37.0-py3.7.egg.zip](https://github.com/JimmXinu/FanFicFare/files/2261031/venv-FanFicFare-2.37.0-py3.7.egg.zip) vs. [pipenv-FanFicFare-2.37.0-py3.7.egg.zip](https://github.com/JimmXinu/FanFicFare/files/2261032/pipenv-FanFicFare-2.37.0-py3.7.egg.zip)

One thing I did notice is that the venv version uses an extracted `.egg`, while pipenv uses some compressed variant? maybe? I don't have very much experience with Python packaging.

**Comment by mcepl** [comment]
> It looks like your virtualenv was using Python 2? I was definitely testing with Python 3.

The whole point of this branch was that it should work both with Python 2 and Python 3. Just saying.

**Comment by hawkrives** [comment]
That's true. I guess I was grasping at straws for why his might work while mine wasn't.

**Comment by mcepl** [comment]
``royalroadl.com now wants to be www.royalroad.com.`` I think this PR should be merged, commits like this have nothing to do with Py3k compatibility, and should be treated separately.

**Comment by JimmXinu** [comment]
FYI, I've put out a test version.

> I've posted a test version of the plugin here:
> http://www.mobileread.com/forums/showthread.php?p=3084025#post3084025
> I've also left the previous test version posted just in case.
> 
> Test version of web service here:
> https://2-37-2-dot-fanficfare.appspot.com/
> 
> Test version of CLI for pip install:  You'll have to get it from the 
> testpypi repository.  This works for me on Debian:
> 
>> `pip install --extra-index-url https://testpypi.python.org/pypi --upgrade FanFicFare`

Outstanding issues:
- ~~Need to test CLI on linux (&MacOS?)~~
- ~~Problems with `--save-cache` feature?~~
- ~~Test outputs on additional readers~~
- ~~`pip` packaging changes~~
- Re-examine Nook cover issue kludge
- Review remaining `encode()`/`decode()` calls for possible replacement with `ensure_text()` or `ensure_binary()`
- mobi output -- was it always this bad?  I think it was...

**Comment by JimmXinu** [comment]
Fixed `mobi` output.  There was a new encoding issue and a few long-standing issues that were introduced back when switched to bs4/html5lib.

To the best of my knowledge, FFF's `mobi` output is now as good as it's ever been.  (Which isn't saying all that much.)

Tested in various combinations on Windows, MacOS, Linux in py2.7, py3.6, py3.7.

Outstanding issues:
- ~~Need to test CLI on linux (&MacOS?)~~
- ~~Problems with `--save-cache` feature?~~
- ~~Test outputs on additional readers~~
- ~~`pip` packaging changes~~
- ~~mobi output -- was it always this bad?  I think it was...~~
- Re-examine Nook cover issue kludge
- Review remaining `encode()`/`decode()` calls for possible replacement with `ensure_text()` or `ensure_binary()`

**Comment by JimmXinu** [comment]
Put the Nook kludge back in.

Remaining `encode()`/`decode()` calls are a motley lot--some I think are needed, some I'm not sure about.  But none seem to be actively broken at the moment.

Outstanding issues:
- ~~Need to test CLI on linux (&MacOS?)~~
- ~~Problems with `--save-cache` feature?~~
- ~~Test outputs on additional readers~~
- ~~`pip` packaging changes~~
- ~~mobi output -- was it always this bad?  I think it was...~~
- ~~Re-examine Nook cover issue kludge~~
- ~~Review remaining `encode()`/`decode()` calls for possible replacement with `ensure_text()` or `ensure_binary()`~~

**Comment by mcepl** [comment]
Congratulations! Good job!

**Pull request merged**
