### PR TITLE
avoid stripping html from description

### PR DESCRIPTION
**Pull request by wassname**
As discussed in [here](https://github.com/JimmXinu/FanFicFare/pull/146#issuecomment-256526566)

### CODE REVIEW

**Comment by wassname** [comment]
I'll just check this on a story with a complex description first (http://royalroadl.com/fiction/4293).

**Comment by wassname** [comment]
Yup it works with that story, including images. Ready to merge.

**Comment by JimmXinu** [comment]
The div class 'description' includes the input and label tags used for controlling the size of the desc on the page.  The div class 'hidden-content' inside it doesn't.

Unless you have seen stories that have div class 'description' without div class 'hidden-content', I suggest changing to find 'hidden-content'.  If you have, I suggest adding code to remove the input and label tags.

I can merge this PR and make that change myself if it's easier.

**Comment by wassname** [comment]
That's a good point, and it's no trouble I'll add it now.

**Comment by JimmXinu** [comment]
Looks good, thanks!

**Pull request merged**
