### PR TITLE
Add adapter for http://wuxiaworld.co/

### PR DESCRIPTION
**Pull request by cryzed**
This is not the same site as https://www.wuxiaworld.com/!

### CODE REVIEW

**Comment by cryzed** [comment]
Don't merge this quite yet, just found a story where date-parsing breaks. That's annoying. Did you parse dates without a 0 prefix for day/month before?

**Comment by JimmXinu** [comment]
wuxiaworld.co is different than wuxiaworld.coM -- because of course it is. 🙄 At least it's a pretty straight-forward looking adapter.

Could use to correct the copyright and add [section] to defaults.ini & plugin-defaults.ini.

Just out of curiosity, is there much content overlap between all these translation sites?

**Comment by cryzed** [comment]
Yes, but this one has some uh..., shall we say, premium stories that other sites are missing.

**Comment by JimmXinu** [comment]
You have a point about config.  I'm not sure if there are no other sites that have nothing to configure, or that they aren't included.  Leave it which ever way you'd prefer.

I'm about to leave for a bit, but I'll pull it and do a test version later tonight.

**Comment by cryzed** [comment]
Got it, I'll just leave it as is for now.

**Pull request merged**
