### PR TITLE
Fix escaping of stories with richly formatted (HTML) chapter content,…

### PR DESCRIPTION
**Pull request by cryzed**
… the second

### CODE REVIEW

**Comment by cryzed** [comment]
@JimmXinu sorry about this.

**Comment by eFrysTon** [comment]
I'm happy to report that applying this patch seems to fix any outstanding escaping issues with webnovel that I'm aware of. I'll do a full download of all the books I follow and check them out in detail now.

**Comment by cryzed** [comment]
Glad to hear that! I only discovered this `isRichFormat` key in the returned chapter data now -- I'm pretty sure it wasn't there before. With that information being accessible, there should no longer be an issue, because I don't have to manually figure out if the chapter content is raw text or HTML.

**Comment by JimmXinu** [comment]
Merged in, but I'd like to figure out #240 before I put out a test version.  Thanks!

**Pull request merged**
