### PR TITLE
feat: append tags into the end of the description (in the worst way p…

### PR DESCRIPTION
**Pull request by BlakeASmith**
…ossible)

### CODE REVIEW

**Comment by BlakeASmith** [comment]
my wife wants the tags in the description. There might be a way to do it with the INI file. I don't want to read the docs

I found the place where the description gets written and changed it right there

**Comment by BlakeASmith** [comment]
I didn't mean to PR from my fork

This code is for my fork only

I am bad at Github

**Comment by BlakeASmith** [comment]
Thank you for your time

**Comment by JimmXinu** [comment]
Showed my wife this and we both got a laugh from it, so thanks.

**Pull request closed without merging**
