### PR TITLE
Fix webnovel.com escaping again

### PR DESCRIPTION
**Pull request by cryzed**
@eFrysTon regarding [this](https://github.com/JimmXinu/FanFicFare/pull/224#issuecomment-329952131). Sorry it took so long, I think this should work properly now for all stories.

### CODE REVIEW

**Comment by eFrysTon** [comment]
Thanks a lot!

But I'm terribly sorry to have to report that their latest website update seems to break metadata parsing, resulting in author names like:

>>>
Dao Is Unfathomable · 
                        Translator: AstralGhost
                        ·
                        Editor: Kurisu
<<<

**Comment by eFrysTon** [comment]
Sorry to report that escaping seems to be broken for https://www.webnovel.com/book/8591840605001105 (Seeking the Flying Sword Path) which ends up full of &lt;p&gt; and &lt;/p&gt;

**Comment by cryzed** [comment]
@eFrysTon please create a new issue for this when you find the time, I'll have to take a look at it at some point.

**Comment by eFrysTon** [comment]
done

**Pull request merged**
