### PR TITLE
New Adapters

### PR DESCRIPTION
**Pull request by gcomyn**
These are 2 new adapters for the 'Lucifael's Writings' and
BuffyGiles.com eFiction sites.

### CODE REVIEW

**Comment by JimmXinu** [comment]
These look pretty good.  But since you're planning to do more, I'm going to be a bit fussy to help you learn the details.  You should be able to make additional changes and add those to the pull req pretty easily after you commit/push to your fork.

**File Names** 

buffygiles.velocitygrass.com vs buffygiles.com.  You've named the file adapter_buffygilescom.py but set the site domain inside buffygiles.velocitygrass.com.  The adapter file should be named after the 'canonical' domain name, which ever that is.

You can also make the adapter accept URLs with both domains with getAcceptDomains() and getSiteURLPattern().  Example:
adapter_mugglenetcom.py:74
adapter_mugglenetcom.py:81

I'd prefer to see adapter_lucifaelff.py named adapter_fanfictionlucifaelcom.py so it's easier to find if/when somebody reports a problem.  I admittedly haven't been very strict about that in past, so you can leave if you prefer.

**`defaults.ini` Files**.  

When adding new adapters, new sections for them should be added to fanficfare/defaults.ini and calibre-plugin/plugin-defaults.ini.  

Sections are (unless I've screwed up) in alphabetical order.  

Sites that use is_adult and username/password should have those commented out as an example for users.  

For fandom/ship/whatever-specific sites, we also add extracategories, extracharacters, extraships as needed.  For an example see defaults.ini:1471  For buffygiles.com, I'd like to see at least `extracategories:Buffy the Vampire Slayer`.  

**warning=# and the error you had and figured out**

Many sites have multiple rating levels and warning numbers.  Most will let you set warning='highest' and get by.  But some site use different warning numbers for different 'ratings' and require you to use the correct number.  

I don't know if those two sites do, but you should test different rating levels and find out.  Or just change it to use the supplied warning number.  One example of the code to use specific warning nums is at adapter_bloodtiesfancom.py:178

Thanks for getting involved and contributing to the project.

**Comment by gcomyn** [comment]
Ok... I'll keep that in mind for the future. 

I did see the extracategories, and set them up for the 4 that I just finished.... one of them I'm going to have to go in and add some sections, since it doesn't get all of the labels (the site doesn't use <span class='label'> for all of the labels... *sigh*)

I know that the sites that I'm 'adapting' for are not really big and active, but I thought I'd start with those that not many people are looking at, so I can cut my teeth on smaller sites.

GComyn

**Comment by JimmXinu** [comment]
My apologies--I was expecting GitHub to send me notices when you updated the pull req and apparently it did not (or I missed them).  I didn't mean to ignore you.

It looks like GitHub wants you to update your fork to match my repository before it will let me merge in the pull req.  I'll merge your changes in and put out a test version once that's done.

Again, sorry for missing your updates.

**Comment by JimmXinu** [comment]
Actually, GitHub does give me directions on how to incorporate your changes and resolve the conflicts myself.  Which I've done: bf277ac00599d98ab72d2aeb906de6b9c2a3b5d8.

The down side is that because the directions having me merging it as a diff, it's not 100% obvious that it's your change that I merged in.  So sorry about that.

While testing this, I found that you included `adapter_rubyquillcom` in `adapters/__init__.py` which doesn't have an adapter file, but commented out `adapter_andromedawebcom` which does.  I reversed those.

I'm going to go ahead and close this PR since it's merged.  If you have other changes or additions, feel free to open another one.  If I don't respond within a couple days next time, please drop me an email.

Thanks for your contribution.

**Pull request closed without merging**
