### PR TITLE
fix deprecation warnings

### PR DESCRIPTION
**Pull request by eli-schwartz**
It's now possible to run fanficfare with `PYTHONWARNINGS=default` exported and no errors logged.

### CODE REVIEW

**Comment by JimmXinu** [comment]
These changes cause the plugin to fail to load for me:
```
calibre 4.20 [64bit]  embedded-python: True is64bit: True
Windows-10-10.0.18362-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.18362')
Python 2.7.16+
Windows: ('10', '10.0.18362', 'SP0', u'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Favourites Menu (1, 0, 5) && EpubMerge (2, 9, 0) && Count Pages (1, 10, 0) && Generate Cover (1, 5, 25) && SplitMergeNew (0, 2, 0) && EpubSplit (2, 9, 0) && FanFicFare (3, 21, 0) && Modify ePub (1, 4, 1) && ColumnSum (2, 1, 0) && Manage Series (1, 2, 9) && View Manager (1, 5, 6) && Quality Check (1, 9, 11) && SmartEject (2, 3, 0) && Reading List (1, 6, 9)
Turning on automatic hidpi scaling
devicePixelRatio: 2.0
logicalDpi: 96.0 x 96.0
physicalDpi: 141.356521739 x 141.402061856
Using calibre Qt style: True
[0.00] Starting up...
[0.00] Initializing db...
[0.03] db initialized
[0.03] Constructing main UI...
Traceback (most recent call last):
  File "site-packages\calibre\gui2\ui.py", line 157, in __init__
  File "site-packages\calibre\gui2\ui.py", line 171, in init_iaction
  File "calibre_plugins.fanficfare_plugin.__init__", line 110, in load_actual_plugin
  File "site-packages\calibre\customize\__init__.py", line 613, in load_actual_plugin
  File "importlib\__init__.py", line 37, in import_module
  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
  File "calibre_plugins.fanficfare_plugin.fff_plugin", line 12, in <module>
  File "site-packages\calibre\customize\zipplugin.py", line 185, in load_module
  File "calibre_plugins.fanficfare_plugin.fanficfare.six", line 318, in <module>
  File "calibre_plugins.fanficfare_plugin.fanficfare.six", line 127, in __init__
TypeError: module.__init__() argument 1 must be string, not unicode
EpubMerge: DEBUG: 2020-07-10 09:29:46,470: calibre_plugins.epubmerge.epubmerge_plugin(157): macmenuhack file_path:C:\Users\user\AppData\Roaming\calibre\plugins\fanficfare_macmenuhack.txt
[2.23] main UI initialized...
[2.23] Started up in 2.23 seconds with 138 books
```
The only change to `six.py` was `from __future__ import absolute_import, division, unicode_literals, print_function` -- which was added to every other file, too.

FFF has to support Calibre's python2 (we're still supporting back to calibre v2.85.1) as well as python3 for the foreseeable future.

I was already reluctant to accept changes to 165 files for no more pressing reason that warnings that I don't even get, but I decided to at least try them.  Now I'm very reluctant.

**Comment by eli-schwartz** [comment]
o_0 vendored code should definitely not get modified.

**Comment by JimmXinu** [comment]
FFF carries around it's own copy of `six.py` because older Calibre versions have an older `six.py` version and `pip` use to have an older version as well.  As I recall, that was the 'recommended' solution from the `six.py` author.

**Comment by eli-schwartz** [comment]
Note that this will become a syntax warning followed by a syntax error as soon as https://bugs.python.org/issue32912 is resolved with a good way to correctly bubble that up. It was supposed to in 3.8/3.9 but then it turned out no one got the warnings if the code was already byte-compiled.

**Comment by eli-schwartz** [comment]
mea culpa, I didn't test this on python2 as my calibre install defaults to python3.

**Comment by JimmXinu** [comment]
I've incorporated the deprecation warning changes, but not the scattershot `__future__` imports because those were still breaking things in Calibre.

**Pull request closed without merging**
