### PR TITLE
Better url parsing

### PR DESCRIPTION
**Pull request by mcepl**
Get storyId for sugarquillnet and siyecouk from the parsed query string.

### CODE REVIEW

**Comment by JimmXinu** [comment]
Applying your favorite code style auto-tool does _not_ make it easier for me to review and consider your changes.

And your changes don't actually fix #652.  URL http://www.sugarquill.net/read.php?chapno=1&storyid=619 still fails because it doesn't match `getSiteURLPattern()`.

**Comment by mcepl** [comment]
> Applying your favorite code style auto-tool does _not_ make it easier for me to review and consider your changes.

I have specifically split changes into significant ones in one commit and NOOP ones, which are in the other one.

> And your changes don't actually fix #652. URL http://www.sugarquill.net/read.php?chapno=1&storyid=619 still fails because it doesn't match `getSiteURLPattern()`.

Fixed.

**Comment by JimmXinu** [comment]
This code still doesn't work with http://www.sugarquill.net/read.php?chapno=1&storyid=619  

And now it doesn't work with http://www.sugarquill.net/read.php?storyid=619 either.

**Comment by mcepl** [comment]
Sorry, there was a typo. Fixed.

**Comment by JimmXinu** [comment]
A basic test (I used https://www.siye.co.uk/siye/viewstory.php?sid=129936) fails immediately.

I'm sorry, but submitting broken code without testing it three times in a row is my limit.  

Show me where you are running into problematic story URLs in the real world and I may reconsider.

**Comment by mcepl** [comment]
I’ve got the URL from https://duckduckgo.com/?q=After+the+End+by+Sugarquill+&t=newext&atb=v247-1&ia=web , and of course, it is your prerogative to use wrong tools for your software. And yes, I am sorry for not being so perfect as you.

**Pull request closed without merging**
