### PR TITLE
Test install package on travis was added

### PR DESCRIPTION
**Pull request by gunmetal313**
Test install package on travis was added

example of travis https://travis-ci.com/gunmetal313/FanFicFare/builds/127708913

https://docs.travis-ci.com/user/tutorial
##  get started with Travis CI
1. Go to Travis-ci.com and Sign up with GitHub.
2. Accept the Authorization of Travis CI. You’ll be redirected to GitHub.
3. Click the green Activate button, and select the repositories you want to use with Travis CI.

### CODE REVIEW

**Comment by JimmXinu** [comment]
Please explain what this is for and why you think it should be included in FFF.

**Comment by mcepl** [comment]
> Please explain what this is for and why you think it should be included in FFF.

Travis is [CI](https://en.wikipedia.org/wiki/Continuous_integration), which allows running the test suite on every commit to GitHub.

**Comment by cryzed** [comment]
Last I checked FFF didn't have a test suite. I think this can be closed.

**Comment by JimmXinu** [comment]
Agreed.  This can be revisited if FFF ever grows a test suite.

**Pull request closed without merging**
