### PR TITLE
Flaresolverr proxy add option to specify protocol

### PR DESCRIPTION
**Pull request by TheCakeIsNaOH**
Add an option to specify the protocol to use for flaresolverr.
This allows usage of flaresolverr over https.

### CODE REVIEW

**Comment by JimmXinu** [comment]
Why is this necessary?  I cannot anything about flaresolverr being able to listen with https?

**Comment by TheCakeIsNaOH** [comment]
I have it behind a reverse proxy.

**Comment by JimmXinu** [comment]
Okay.  

Fair warning though, I'm not going to the effort of setting up flaresolverr behind an https to test it and I'm not supporting anyone trying to do so.

**Comment by TheCakeIsNaOH** [comment]
Yup, I saw your comment in the issue about not wanting extra things to support. 
That is no problem, I can always make another PR if it gets broken in the future.

**Pull request merged**
