### PR TITLE
add ability to download AO3 workskin if scraping styles is enabled

### PR DESCRIPTION
**Pull request by niacdoial**
If the "keep_html_attrs" config parameter includes "style", add the workskin (for AO3 works that have one) to the ebook's stylesheet.

### CODE REVIEW

**Comment by JimmXinu** [comment]
I'd like a few changes before accepting this:

1. This should be a new configuration switch such as `use_workskin`.
   Inclusion of `style` in `keep_html_attrs` shouldn't be the controlling element.  If anything, an author using inline styles probably indicates they *don't* use workskin CSS.

   Search for `use_view_full_work` in `fanficfare/configurable.py` (in two places), `fanficfare/defaults.ini`, and `calibre-plugin/plugin-defaults.ini` for examples of what to add where.  

3. I'd appreciate comments in `story.py` and `base_writer.py` about `extra_css` that refer to the new setting.

4. FFF is still back compatible to old versions of Calibre in python2.  Please use `from ..six import text_type as unicode` and `unicode` instead of `str` for consistency.

**Comment by niacdoial** [comment]
1. OK, I will do that. Should that new option be false by default ?
2. OK.
3. ... I feel like I should have thought of it myself, oh well.

**Comment by JimmXinu** [comment]
1. Yes.  Commented out and false is what we usually do.  Thanks.

**Comment by niacdoial** [comment]
done!
I also spotted while searching that AO3 was not the only site to use use_view_full_work

**Comment by niacdoial** [comment]
thanks!

**Comment by JimmXinu** [comment]
That pointed out to me that squidgeworld also shares all settings with AO3, so I made some more lists.

However, while testing this, it occurs that **the CSS order should be workskin, then `output_css` setting** so user can override workskin in `personal.ini`.

**Comment by niacdoial** [comment]
oh. well, I got a new commit out that fixes that, if you didn't do so on your side yet

**Comment by chocolatechipcats** [comment]
@niacdoial just wanted to thank you personally for letting me download a story that had tricky CSS that I couldn't get working manually!

**Pull request merged**
