### PR TITLE
Add reformating to lightnovelgate

### PR DESCRIPTION
**Pull request by Rikkitp**
By default lightnovelgate.com often gives a badly formatted story (even with invalid html).
This fixes most problems.

### CODE REVIEW

**Comment by JimmXinu** [comment]
Can you give a few example story URLs of what you're trying to fix and a brief description of your fix?  

I'm especially interested in knowing whether this addresses problems with the site, or problems with the HTML uploaded to the site by the authors.

FYI, I'm traveling, so I'm probably not going to integrate PRs until later in the week.

**Comment by Rikkitp** [comment]
broken paragraph
http://lightnovelgate.com/chapter/the_legendary_moonlight_sculptor/chapter_222

extra space
http://lightnovelgate.com/chapter/overlord_ln/chapter_6
http://lightnovelgate.com/chapter/transcending_the_nine_heavens/chapter_1

I will search for other examples.

**Comment by Rikkitp** [comment]
I added more comments to code. Will this describe enough?

**Comment by Rikkitp** [comment]
Fixed.

Added `fix_excess_space` option with default value `true`. Some books, like "The Legendary Moonlight Sculptor", is impossible to read without it.

**Comment by JimmXinu** [comment]
Thanks!

**Pull request merged**
